try different mac ones

diff --git a/.github/workflows/test-simple-with-ss3-artifacts.yml b/.github/workflows/test-simple-with-ss3-artifacts.yml
--- a/.github/workflows/test-simple-with-ss3-artifacts.yml
+++ b/.github/workflows/test-simple-with-ss3-artifacts.yml
@@ -43,9 +43,9 @@ jobs:
         if: startsWith(matrix.os, 'macos-')
         run: brew install bash
 
-      - name: Set SHELL to bash 5 on macOS
-        if: startsWith(matrix.os, 'macos-')
-        run: echo "/opt/homebrew/bin/bash" >> $GITHUB_PATH
+      # - name: Set SHELL to bash 5 on macOS
+      #   if: startsWith(matrix.os, 'macos-')
+      #   run: echo "/opt/homebrew/bin/bash" >> $GITHUB_PATH
 
       - name: Find latest successful build-ss3 workflow run in nmfs-ost/ss3-source-code
         id: get_run
@@ -126,8 +126,8 @@ jobs:
             "/repos/nmfs-ost/ss3-source-code/actions/artifacts/$found_id/zip" > "ss3_artifacts/$os_artifact.zip"
 
       - name: Download artifact for this OS mac
-        id: download_artifact-mac
-        if: startsWith(matrix.os, 'macos-')
+        id: download_artifact-mac-silicon
+        if: runner.os == 'macos-latest'
         shell: /opt/homebrew/bin/bash {0}
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -167,7 +167,47 @@ jobs:
             -H "Authorization: Bearer $GH_TOKEN" \
             "/repos/nmfs-ost/ss3-source-code/actions/artifacts/$found_id/zip" > "ss3_artifacts/$os_artifact.zip"
 
-
+      - name: Download artifact for this OS mac
+        id: download_artifact-mac-intel
+        if: runner.os == 'macos-13'
+        shell: /opt/homebrew/bin/bash {0}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -e
+          mkdir -p ss3_artifacts
+          os_artifact="${{ matrix.artifact_name }}"
+          readarray -t artifacts < <(echo '${{ steps.list_artifacts.outputs.artifacts }}' | jq -r '.[] | @base64')
+          if [[ ${#artifacts[@]} -eq 0 ]]; then
+            echo "No artifacts found."
+            exit 1
+          fi
+          echo "Available artifacts:"
+          for artifact in "${artifacts[@]}"; do
+            echo "${artifact}" | base64 --decode | jq -r '.name'
+          done
+          found_id=""
+          for artifact in "${artifacts[@]}"; do
+            _jq() {
+              echo "${artifact}" | base64 --decode | jq -r "${1}"
+            }
+            name=$(_jq '.name')
+            id=$(_jq '.id')
+            if [[ "$name" == "$os_artifact" ]]; then
+              found_id="$id"
+              break
+            fi
+          done
+          if [ -z "$found_id" ]; then
+            echo "Artifact $os_artifact not found!"
+            exit 1
+          fi
+          # Download the artifact
+          echo "Downloading artifact: $os_artifact"
+          gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer $GH_TOKEN" \
+            "/repos/nmfs-ost/ss3-source-code/actions/artifacts/$found_id/zip" > "ss3_artifacts/$os_artifact.zip"
       - name: Unzip SS3 executable
         shell: bash
         run: |
